# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

lane :runway_test do
  # See https://api-docs.runway.team/#tag/buildDistro/operation/uploadBucketBuild for parameter details
  upload_to_runway(
    file_path: 'file_path',
    bucket_id: 'bucket_id',
    app_id: 'app_id',
    tester_notes: 'This is a test upload!',
    ci_build_info: {
          buildIdentifier: 'build_identifier',
          commitMessage: 'some commit message1241',
          commitAuthor: 'jp2014',
          branch: 'branch',
          integrationId: 'azure-ci',
          commitHash: 'commit_hash',
          commitUrl: 'commit_url',
          url: 'url',
          workflowData: {
            workflowId: 'workflow_id',
            workflowName: 'workflow_name'
          }
        }
  )
end
